
version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 3rrHhbir
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis:3.0.5
  app:
    build: .
    environment:
      MYAPP_DATABASE_USERNAME: root
      MYAPP_DATABASE_PASSWORD: 3rrHhbir
      MYAPP_DATABASE_HOST: db
  web:
    extends:
      service: app
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
      - redis
  # worker:
  #   extends:
  #     service: app
  #   command: bundle exec sidekiq -q notification
  #   volumes:
  #     - .:/app
  #   links:
  #     - db
  #     - redis
  #
volumes:
  db-data:
    driver: local

